# A sample for this SDK config mapping to each service providers
# The config root is "provider" here, you can modify as you need.
#
## Provider `Dashscope`
### Model Series `qwen`
#### The only configuration is `apiKey`
#
provider.dashscope.qwen.apiKey=
#
## Provider `Azure OpenAI`
### Model Deployment `gpt-4o`
#### The `apiKey`,`resourceName`,`deployment` and `apiVersion` for this deployment
#
provider.azure.openai.gpt-4o.apiKey=
provider.azure.openai.gpt-4o.resourceName=
provider.azure.openai.gpt-4o.deployment=
provider.azure.openai.gpt-4o.apiVersion=
#
## Provider `Volces`
### The `apiKey` is applied for the whole provider.
#
provider.volces.apiKey=
#
### The Models, each mapped to a deployment
#
provider.volces.model.doubao-pro-32k=
#
## Provider `Mirage`
#
provider.mirage.domain=
provider.mirage.client_code=
provider.mirage.client_secret=