# A sample for this SDK config mapping to each service providers
# The config root is "provider" here, you can modify as you need.
#
## Provider `Dashscope`
### Model Series `qwen`
#### The only configuration is `apiKey`
#
provider.dashscope.qwen.apiKey=1
#
## Provider `Azure OpenAI`
### Model Deployment `gpt-4o`
#### The `apiKey`,`resourceName`,`deployment` and `apiVersion` for this deployment
#
provider.azure.openai.gpt-4o.apiKey=1
provider.azure.openai.gpt-4o.resourceName=2
provider.azure.openai.gpt-4o.deployment=3
provider.azure.openai.gpt-4o.apiVersion=4
#
## Provider `Volces`
### The `apiKey` is applied for the whole provider.
#
provider.volces.apiKey=1
#
### The Models, each mapped to a deployment
#
provider.volces.model.doubao-pro-32k=1
#
## Provider `Mirage`
#
provider.mirage.domain=x
provider.mirage.client_code=x
provider.mirage.client_secret=x