package io.github.sinri.AiOnHttpMix.provider.azure.openai.chatgpt.message;

import io.github.sinri.AiOnHttpMix.provider.azure.openai.chatgpt.tool.ChatGPTToolCall;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;

import javax.annotation.Nullable;
import java.util.List;

public interface ChatGPTMessageInRequest extends ChatGPTMessage {
    static ChatGPTMessageInRequest create() {
        return new ChatGPTMessageImpl();
    }

    /**
     * @param content The contents of the system message.
     * @param name    An optional name for the participant. Provides the model
     *                information to differentiate between participants of the same
     *                role.
     */
    static ChatGPTMessageInRequest createAsSystem(String content, @Nullable String name) {
        var j = new JsonObject()
                .put("role", "system")
                .put("content", content);
        if (name != null) {
            j.put("name", name);
        }
        return new ChatGPTMessageImpl(j);
    }

    /**
     * @param content The contents of the user message.
     * @param name    An optional name for the participant. Provides the model
     *                information to differentiate between participants of the same
     *                role.
     */
    static ChatGPTMessageInRequest createAsUser(String content, @Nullable String name) {
        var j = new JsonObject()
                .put("role", "user")
                .put("content", content);
        if (name != null) {
            j.put("name", name);
        }
        return new ChatGPTMessageImpl(j);
    }

    /**
     * @param content The contents of the assistant message. Required unless
     *                tool_calls or function_call is specified.
     * @param name    An optional name for the participant. Provides the model
     *                information to differentiate between participants of the same
     *                role.
     * @param refusal The refusal message by the assistant.
     */
    static ChatGPTMessageInRequest createAsAssistant(
            String content,
            @Nullable String name,
            @Nullable String refusal) {
        var j = new JsonObject()
                .put("role", "assistant")
                .put("content", content);
        if (name != null) {
            j.put("name", name);
        }
        if (refusal != null) {
            j.put("refusal", refusal);
        }
        return new ChatGPTMessageImpl(j);
    }

    /**
     * @param content   The contents of the assistant message. Required unless
     *                  tool_calls or function_call is specified.
     * @param toolCalls The tool calls generated by the model, such as function
     *                  calls.
     * @param name      An optional name for the participant. Provides the model
     *                  information to differentiate between participants of the
     *                  same role.
     * @param refusal   The refusal message by the assistant.
     */
    static ChatGPTMessageInRequest createAsToolCall(
            @Nullable String content,
            List<ChatGPTToolCall> toolCalls,
            @Nullable String name,
            @Nullable String refusal) {
        var j = new JsonObject()
                .put("role", "assistant");
        if (content != null) {
            j.put("content", content);
        }
        if (name != null) {
            j.put("name", name);
        }
        if (refusal != null) {
            j.put("refusal", refusal);
        }
        JsonArray array = new JsonArray();
        toolCalls.forEach(tc -> {
            JsonObject object = tc.cloneAsJsonObject();
            array.add(object);
        });
        j.put("tool_calls", array);
        return new ChatGPTMessageImpl(j);
    }

    /**
     * @param content      The contents of the tool message.
     * @param tool_call_id Tool call that this message is responding to.
     */
    static ChatGPTMessageInRequest createAsToolOutput(@Nullable String content, String tool_call_id) {
        var j = new JsonObject();
        j.put("role", "tool");
        j.put("content", content);
        j.put("tool_call_id", tool_call_id);
        return new ChatGPTMessageImpl(j);
    }

    static ChatGPTMessageInRequest wrap(JsonObject jsonObject) {
        return new ChatGPTMessageImpl(jsonObject);
    }

}
